production:
  clients:
    default:
      hosts:
        - localhost:27017
      database: <%= ENV["MONGODB_DATABASE"] || 'qidb_production' %>
      username: <%= ENV["MONGODB_USERNAME"] || 'qidb_user' %>
      password: <%= ENV["MONGODB_PASSWORD"] || 'qidb_pass'%>
development:
  clients:
    default:
      database: qidb_development
      hosts:
        - <%= (ENV["MONGODB_HOST"] || 'localhost') + ':27017' %>
test:
  clients:
    default:
      database: qidb_test
      hosts:
        - <%= (ENV["MONGODB_HOST"] || 'localhost') + ':27017' %>
